Add Filtering examples
iann0036/former2 pull request #104
Opened 2020-09-06 13:22 UTC by jlandowner

Close #87

2020-09-06 22:02 UTC, iann0036 requested changes

2020-09-06 22:02 UTC, iann0036 commented on README.md
> +Former2 CLI has the advantage of being able to use your local AWS CLI credentials without using access keys.
I'd rather not have this. It's somewhat misleading and detracts from the main website.

2020-09-06 23:35 UTC, jlandowner commented on README.md
> +Former2 CLI has the advantage of being able to use your local AWS CLI credentials without using access keys.
I thought this did not detract from the value of the site and would help a proper understanding of security, but remove it as it is an extra addition.

2020-09-07 14:55 UTC, jlandowner commented
I fixed my update.

2020-09-07 22:01 UTC, iann0036 approved these changes

2020-09-07 22:01 UTC, merged